### ISSUE TITLE
Documentação

### ISSUE THREAD

**Issue by dlhenke** [TimeShareSolucoes/boletobr#2]
Há documentação?
Ou exemplos de uso ??
Grato ...

**Comment by gabrielrb** [comment]
Olá @dlhenke. Vamos providenciar ainda esse ano uma documentação/exemplos de uso.
Não priorizamos ainda essa parte, pois precisamos criar um "render" html para esse projeto.

Usamos ele em produção, e diariamente são gerados através desse componente alguns milhões de reais em recebíveis, mas nosso "render" foi criado em DevExpress... Por tal motivo não compartilhamos ainda.

**Comment by davidcoopermine** [comment]
Ola @gabrielrb Bacana a dll. Poderia me enviar os exemplos? Tenho o DevExpress.
Poderia enviar por email? david@nova-cloud.com.br

**Comment by gabrielrb** [comment]
Oi @dlhenke  / @davidcoopermine . Lançaremos um RENDER em DevExpress ainda esse mês direto na biblioteca.
