### ISSUE TITLE
Iniciando com BoletoBR

### ISSUE THREAD

**Issue by jrsiqueira** [TimeShareSolucoes/boletobr#5]
Boa Tarde

Por gentileza, algum colega teria algum exemplo de como iniciar a geração de boletos para CEF? Eu já utilizava o Boleto.Net e acabei descobrindo em pesquisa pelo GitHub este projeto e gostei da apresentação e aparenta ser mais simples sua implementação. 

Procurei em todo o repositório por exemplos, manuais mais não tive sucesso.

Obrigado.

José Roberto Siqueira

**Comment by gabrielrb** [comment]
Bom dia @jrsiqueira .

Lançaremos até o fim do ano uma tela de demonstração. o @kalleyaoliveira  está desenvolvendo. Por enquanto só nossos testes unitários podem te auxiliar.

Usamos em produção com diversos bancos, e diariamente são emitidos milhares de reais em boletos pelo nosso componente, mas pecamos em oferecer documentação a comunidade.

Sorry.
